package site.neurotriumph.www.constant;

public enum TokenMarker {
  AUTHENTICATION,
  PASSWORD_UPDATE_CONFIRMATION,
  EMAIL_UPDATE_CONFIRMATION,
  USER_DELETE_CONFIRMATION,
  REGISTRATION_CONFIRMATION
}
